/** @import { IRObjectType, IRTable, IRType, SchemaIR } from './irTypes.js' */
import fs from 'node:fs';

/** Every generated source file starts with this, so stale or mixed generations can be found. */
export const GENERATED_MARKER = '// @generated by @harperfast/schema-codegen';

/**
 * @param {SchemaIR} ir
 * @returns {string}
 */
export function generatedHeader(ir) {
	return `${GENERATED_MARKER} from ${ir.generator ?? 'a schema IR'} (schema ${ir.schemaHash}). Do not edit.\n`;
}

/**
 * @param {string} fileName a file in ./runtime
 * @returns {string}
 */
export function readRuntimeSource(fileName) {
	return fs.readFileSync(new URL(`./runtime/${fileName}`, import.meta.url), 'utf8');
}

/**
 * Splits a description into comment lines; `*\/` and `/*` are broken up so the text can never
 * close or open a block comment.
 * @param {string | undefined} text
 * @returns {string[]}
 */
export function commentLines(text) {
	if (!text) return [];
	return String(text)
		.replace(/\*\//g, '* /')
		.replace(/\/\*/g, '/ *')
		.split(/\r\n|\r|\n/)
		.map((line) => line.trimEnd());
}

/**
 * @param {number} codePoint
 * @returns {boolean}
 */
function isControl(codePoint) {
	return (
		codePoint < 0x20 ||
		(codePoint >= 0x7f && codePoint < 0xa0) ||
		codePoint === 0x2028 ||
		codePoint === 0x2029
	);
}

/**
 * A Swift string literal for any text. Lone surrogates (impossible in a Swift string) become U+FFFD.
 * @param {string} value
 * @returns {string}
 */
export function swiftString(value) {
	let literal = '"';
	for (const character of String(value)) {
		const codePoint = /** @type {number} */ (character.codePointAt(0));
		if (character === '\\') literal += '\\\\';
		else if (character === '"') literal += '\\"';
		else if (character === '\n') literal += '\\n';
		else if (character === '\r') literal += '\\r';
		else if (character === '\t') literal += '\\t';
		else if (codePoint >= 0xd800 && codePoint <= 0xdfff) literal += '\\u{FFFD}';
		else if (isControl(codePoint)) literal += `\\u{${codePoint.toString(16).toUpperCase()}}`;
		else literal += character;
	}
	return `${literal}"`;
}

/**
 * A Kotlin string literal for any text; `$` is escaped so nothing is interpolated.
 * @param {string} value
 * @returns {string}
 */
export function kotlinString(value) {
	let literal = '"';
	for (const character of String(value)) {
		const codePoint = /** @type {number} */ (character.codePointAt(0));
		if (character === '\\') literal += '\\\\';
		else if (character === '"') literal += '\\"';
		else if (character === '$') literal += '\\$';
		else if (character === '\n') literal += '\\n';
		else if (character === '\r') literal += '\\r';
		else if (character === '\t') literal += '\\t';
		else if (character === '\b') literal += '\\b';
		else if (isControl(codePoint) || (codePoint >= 0xd800 && codePoint <= 0xdfff)) {
			literal += `\\u${codePoint.toString(16).toUpperCase().padStart(4, '0')}`;
		} else literal += character;
	}
	return `${literal}"`;
}

/**
 * Finds the attribute edges that make a value type contain itself: a direct (not through an
 * array) reference from a table or nested type to one in the same strongly connected component.
 * Swift structs cannot hold such an edge by value.
 * @param {SchemaIR} ir
 * @returns {Set<string>} keys `<owner>#<attribute>`, where owner is a typeName
 */
export function recursiveValueEdges(ir) {
	/** @type {Map<string, { attribute: string, target: string }[]>} */
	const graph = new Map();
	const tablesByKey = new Map(
		ir.tables.map((table) => [`${table.database}\u0000${table.name}`, table]),
	);
	const typesByName = new Map(ir.types.map((type) => [type.name, type]));
	/**
	 * @param {IRType} type
	 * @returns {string | null}
	 */
	const directTarget = (type) => {
		if (type.kind === 'object') return typesByName.get(type.type)?.typeName ?? null;
		if (type.kind === 'record')
			return tablesByKey.get(`${type.database}\u0000${type.table}`)?.typeName ?? null;
		return null;
	};
	/** @param {IRTable | IRObjectType} owner */
	const addOwner = (owner) => {
		const edges = [];
		for (const attribute of owner.attributes) {
			const target = directTarget(attribute.type);
			if (target) edges.push({ attribute: attribute.name, target });
		}
		graph.set(owner.typeName, edges);
	};
	ir.tables.forEach(addOwner);
	ir.types.forEach(addOwner);

	/** @type {Map<string, number>} */
	const component = new Map();
	/** @type {Map<string, number>} */
	const index = new Map();
	/** @type {Map<string, number>} */
	const lowLink = new Map();
	/** @type {string[]} */
	const stack = [];
	const onStack = new Set();
	let counter = 0;
	let components = 0;
	/** @param {string} node */
	const connect = (node) => {
		index.set(node, counter);
		lowLink.set(node, counter);
		counter++;
		stack.push(node);
		onStack.add(node);
		for (const { target } of graph.get(node) ?? []) {
			if (!index.has(target)) {
				connect(target);
				lowLink.set(
					node,
					Math.min(
						/** @type {number} */ (lowLink.get(node)),
						/** @type {number} */ (lowLink.get(target)),
					),
				);
			} else if (onStack.has(target)) {
				lowLink.set(
					node,
					Math.min(
						/** @type {number} */ (lowLink.get(node)),
						/** @type {number} */ (index.get(target)),
					),
				);
			}
		}
		if (lowLink.get(node) === index.get(node)) {
			let member;
			do {
				member = /** @type {string} */ (stack.pop());
				onStack.delete(member);
				component.set(member, components);
			} while (member !== node);
			components++;
		}
	};
	for (const node of graph.keys()) {
		if (!index.has(node)) connect(node);
	}

	const edges = new Set();
	for (const [owner, ownerEdges] of graph) {
		for (const { attribute, target } of ownerEdges) {
			if (component.get(owner) === component.get(target)) edges.add(`${owner}#${attribute}`);
		}
	}
	return edges;
}
